services:
  default:
      container_name: default
      build: .
      volumes:
        - ./app:/usr/src/app/

  ev_logger:
    container_name: ev_logger
    build: .
    volumes:
      - ./app:/usr/src/app/
    
    # Default. Emits labels to stdout every 300 seconds and no identation.
    command: ev_logger.py

    environment:
      - TZ=Australia/Sydney
      - EV_LOGGER_PREFIX=APP_CONTOSO_MS                       # Mandatory. Prefix for the environment variables.
      # - EV_LOGGER_INDENT=2                                  # Optional. JSON indentation. Default is 0.
      # - EV_LOGGER_INTERVAL=300                              # Optional. Interval (sec) to log. Default is 300.
      # - EV_LOGGER_INTERVAL=0                                # Example of logging only once.
      # - EV_LOGGER_INTERVAL=60                               # Example of logging every minute.

      # The remainder of the environment variables are examples of the labels that will be emitted.
      # They all start with the prefix APP_CONTOSO_MS, which is defined by EV_LOGGER_PREFIX.
      - APP_CONTOSO_MS_INSTANCE=my-instance
      - APP_CONTOSO_MS_MANAGED-BY=my-team
      - APP_CONTOSO_MS_PART-OF=my-collection
      - APP_CONTOSO_MS_INVENTORY_0_NAME=my-app
      - APP_CONTOSO_MS_INVENTORY_0_VERSION=v1
      - APP_CONTOSO_MS_INVENTORY_0_COMPONENT=my-component
      - APP_CONTOSO_MS_INVENTORY_1_NAME=my-app2
      - APP_CONTOSO_MS_INVENTORY_1_VERSION=v2
      - APP_CONTOSO_MS_INVENTORY_1_COMPONENT=my-component2
