services:
  soe:
    container_name: soe
    image: python_soe:latest
    build: soe/.
    environment:
      - TZ=Australia/Sydney
  
  default:
    build: 
      context: .
      args:
        - APP_SOURCE=default
    
    container_name: default
    image: python_default:latest
    volumes:
      - ./apps/default:/home/appuser/app/
  
  blackvue:
    build: 
      context: .
      args:
        - APP_SOURCE=blackvue
    
    container_name: blackvue
    image: python_blackvue:latest
    volumes:
      - ./apps/blackvue:/home/appuser/app/
    restart: on-failure

    environment:
      - TZ=Australia/Sydney
    
    # pass in parameters to the CMD
    command: [
      "app.py", 
      "--host", "192.168.0.111"
    ]

  ev_logger:
    container_name: ev_logger
    image: ev_logger:latest
    build: .
    volumes:
        - ./apps/default:/usr/src/app/
    
    # Default. Emits labels to stdout every 300 seconds and no identation.
    command: ev_logger.py

    environment:
      - TZ=Australia/Sydney
      - EV_LOGGER_PREFIX=APP_CONTOSO_MS                       # Mandatory. Prefix for the environment variables.
      # - EV_LOGGER_SYSLOG=0                                  # Optional. Set to 1 to enable syslog. Default is 0.
      # - EV_LOGGER_INDENT=2                                  # Optional. JSON indentation. Default is 0.
      # - EV_LOGGER_INTERVAL=300                              # Optional. Interval (sec) to log. Default is 300.
      # - EV_LOGGER_INTERVAL=0                                # Example of logging only once.
      # - EV_LOGGER_INTERVAL=60                               # Example of logging every minute.

      # The remainder of the environment variables are examples of the labels that will be emitted.
      # They all start with the prefix APP_CONTOSO_MS, which is defined by EV_LOGGER_PREFIX.
      - APP_CONTOSO_MS_INSTANCE=my-instance
      - APP_CONTOSO_MS_MANAGED-BY=my-team
      - APP_CONTOSO_MS_PART-OF=my-collection
      - APP_CONTOSO_MS_INVENTORY__0__NAME=my-app
      - APP_CONTOSO_MS_INVENTORY__0__VERSION=v1
      - APP_CONTOSO_MS_INVENTORY__0__COMPONENT=my-component
      - APP_CONTOSO_MS_INVENTORY__1__NAME=my-app2
      - APP_CONTOSO_MS_INVENTORY__1__VERSION=v2
      - APP_CONTOSO_MS_INVENTORY__1__COMPONENT=my-component2
