teamcity:
  config:
    url: http://192.168.0.31:8111
    # build_type: MyProject_MyBuild
    # build_number: 1
    # build_timeout: 60
    # build_interval: 5
    # build_properties:
    #   - key: property1
    #     value: value1
    #   - key: property2
    #     value: value2